// Rotating daily quotes about time, mortality, and purpose.
// Selected once per day (based on day-of-year) so the same quote persists all day.
window.REMAINING_DAYS_QUOTES = [
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The only easy day was yesterday.", author: "Navy SEALs" },
  { text: "Stay hard.", author: "David Goggins" },
  { text: "Get comfortable being uncomfortable.", author: "David Goggins" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "I hated every minute of training. But I said, don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "Impossible is just a big word thrown around by small men.", author: "Muhammad Ali" },
  { text: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and on the road.", author: "Muhammad Ali" },
  { text: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa" },
  { text: "Every champion was once a contender who refused to give up.", author: "Rocky Balboa" },
  { text: "Everybody has a plan until they get punched in the mouth.", author: "Mike Tyson" },
  { text: "I've missed over 9,000 shots. I've lost almost 300 games. That is why I succeed.", author: "Michael Jordan" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Mamba mentality is about 4 AM workouts, doing more than the next guy.", author: "Kobe Bryant" },
  { text: "Rest at the end, not in the middle.", author: "Kobe Bryant" },
  { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
  { text: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Victory belongs to the most persevering.", author: "Napoleon Bonaparte" },
  { text: "Do not pray for an easy life; pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "Blood, sweat and respect. First two you give, last one you earn.", author: "Dwayne Johnson" },
  { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "Jim Rohn" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "George Lorimer" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Nobody cares. Work harder.", author: "Cameron Hanes" },
  { text: "Grind while they sleep. Learn while they party. Live like they dream.", author: "Anonymous" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "Excuses are tools of the incompetent used to build monuments of nothingness.", author: "Anonymous" },
  { text: "A warrior is not defined by his sword, but by the fire in his eyes.", author: "Anonymous" },
  { text: "The distance between dreams and reality is called action.", author: "Anonymous" },
  { text: "You don't rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Fall seven times. Stand up eight.", author: "Japanese Proverb" },
  { text: "The only limit to your impact is your imagination and commitment.", author: "Tony Robbins" },
  { text: "Whether you think you can, or you think you can't — you're right.", author: "Henry Ford" },
  { text: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain" }
];
