// Rotating daily quotes about time, mortality, and purpose.
// Selected once per day (based on day-of-year) so the same quote persists all day.
window.REMAINING_DAYS_QUOTES = [
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
  { text: "How we spend our days is, of course, how we spend our lives.", author: "Annie Dillard" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "Time is the wisest counsellor of all.", author: "Pericles" },
  { text: "The trouble is, you think you have time.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", author: "Mother Teresa" },
  { text: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { text: "The bad news is time flies. The good news is you're the pilot.", author: "Michael Altshuler" },
  { text: "You may delay, but time will not.", author: "Benjamin Franklin" },
  { text: "Time is what we want most, but what we use worst.", author: "William Penn" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Ordinary people think merely of spending time. Great people think of using it.", author: "Arthur Schopenhauer" },
  { text: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
  { text: "Time flies over us, but leaves its shadow behind.", author: "Nathaniel Hawthorne" },
  { text: "The key is in not spending time, but in investing it.", author: "Stephen R. Covey" },
  { text: "Memento mori — remember that you must die.", author: "Ancient Roman" },
  { text: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll" },
  { text: "Time is free, but it's priceless. You can't own it, but you can use it.", author: "Harvey Mackay" },
  { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { text: "The only reason for time is so that everything doesn't happen at once.", author: "Albert Einstein" },
  { text: "Don't count every hour in the day, make every hour in the day count.", author: "Muhammad Ali" },
  { text: "Time and tide wait for no man.", author: "Geoffrey Chaucer" },
  { text: "We must use time wisely and forever realize that the time is always ripe to do right.", author: "Nelson Mandela" },
  { text: "The way we spend our time defines who we are.", author: "Jonathan Estrin" },
  { text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Jim Rohn" },
  { text: "Death smiles at us all; all we can do is smile back.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "The days are long, but the years are short.", author: "Gretchen Rubin" },
  { text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.", author: "Goethe" },
  { text: "You will never find time for anything. If you want time, you must make it.", author: "Charles Buxton" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "It's not the days in your life, but the life in your days that counts.", author: "Adlai Stevenson II" },
  { text: "One day, or day one. You decide.", author: "Anonymous" },
  { text: "Nothing is a waste of time if you use the experience wisely.", author: "Auguste Rodin" }
];
